services:
  - type: web
    name: ai-resume-builder-backend
    runtime: python
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend/src && python main.py
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENAI_API_BASE
        value: https://api.openai.com/v1
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        value: "a-secure-random-secret-key-for-render-deployment"
      - key: RENDER
        value: "true"
      - key: PYTHONPATH
        value: "/opt/render/project/src/backend"

  - type: web
    name: ai-resume-builder-frontend
    runtime: static
    plan: free
    buildCommand: cd frontend && pnpm install && pnpm run build
    staticPublishPath: frontend/dist
    envVars:
      - key: VITE_API_BASE_URL
        fromService:
          name: ai-resume-builder-backend
          type: web
          envVarKey: RENDER_EXTERNAL_URL
    domains:
      - ai-resume-builder-frontend.onrender.com